spring:
  application:
    name: backend
  profiles:
    active: dev


    server:
      port: 6969
  servlet:
    context:
      path: /menus

    data:
      mongodb:
        host: localhost
        port: 27017
        database: menus_mvp_1
  graphql:
    graphiql:
    enabled: true
    path: /graph

validation:
  regex:
    imageUrl: "^(https?://[^\\s]+/[^\\s]+\\.(?i)(jpg|jpeg|png|gif|bmp|webp))$"
